### ISSUE TITLE
MAJOR BUG: New user configuration file each time a command is ran.

### ISSUE THREAD

**Issue by SirObby** [SirObby/abouncingsealbot#3]
Suspected cause: Faulty configuration file checker.
Fault: A new file allegedly is created each time `CheckConfig();` is ran in configs.hpp.

Nothing is directly affected by this issue. Storage issues are a concern.

UPDATE:
Temporary Fix: Files in /configs/ with the name length of 20 are deleted.

**Comment by SirObby** [comment]
Affects leveling system.

**Comment by VeryHolyCheeeese** [comment]
YIIIKES

**Comment by SirObby** [comment]
Leveling is not affected by this*

**Comment by VeryHolyCheeeese** [comment]
Good

**Comment by SirObby** [comment]
A new file gets created every time a command is ran by a user due to a faulty configuration file checker.
